70 single client
yalla-coop/chiltern-music-therapy pull request #111
Opened 2021-04-06 06:34 UTC by RamyAlshurafa

#### Issues this PR relates to
#70 

=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-04-06 15:47 UTC, thejoefriel requested changes
- [ ] If there are no programmes no need to show this card as it doesn't make sense. Just show nothing 
![image](https://user-images.githubusercontent.com/19708921/113738178-98866d80-96f6-11eb-987e-3dd77c3b662c.png)

2021-04-06 15:47 UTC, thejoefriel commented on client/src/pages/Therapist/SingleClient/index.js
> +          {ellipsis && (
Instead of showing the background on this page, turn this into a link that will take them to the Client History page you've created (this is the acceptance criteria in the issue currently not ticked)

The reason for this is just in case the background is actually really really long, we instead want them to always view that on the separate page.

2021-04-06 15:47 UTC, thejoefriel commented on client/src/pages/Therapist/SingleClient/style.js
> +  max-width: 948px;
We have a max-width prop for content in the general layout you can use instead

2021-04-06 15:47 UTC, thejoefriel commented on server/modules/therapist-client/model/find.js
> +  const res = await query(sql, values, client);
Is the client argument here needed since you don't use it in the use case?

2021-04-07 11:27 UTC, RamyAlshurafa commented on client/src/pages/Therapist/SingleClient/index.js
> +          {ellipsis && (
done

2021-04-07 11:30 UTC, RamyAlshurafa commented on client/src/pages/Therapist/SingleClient/style.js
> +  max-width: 948px;
done

2021-04-07 11:30 UTC, RamyAlshurafa commented on client/src/pages/Therapist/SingleClient/style.js
> +  max-width: 948px;
the one in the wrapper is enough i think so removed it

2021-04-07 11:32 UTC, RamyAlshurafa commented on server/modules/therapist-client/model/find.js
> +  const res = await query(sql, values, client);
i used to keep it, so if anyone else use it from another space with transaction can use, its optional and without it (undefined here) the query will work as normal query

2021-04-07 12:57 UTC, thejoefriel approved these changes

2021-04-07 12:57 UTC, merged