47 therapist can add profile(front end)
yalla-coop/chiltern-music-therapy pull request #112
Opened 2021-04-06 11:54 UTC by fadeomar

#### Issues this PR relates to
#47 
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-04-06 16:44 UTC, thejoefriel requested changes

2021-04-06 16:44 UTC, thejoefriel commented on client/src/pages/Therapist/Profile/index.js
> +        <Col w={[4, 6, 4]}>
You can see that the inputs are not in line (pic below)
This is because the biography input has a label. What I'd suggest is add some paddingTop to this Col (either in line style of import Col into style file) which then compensates for the line height of the label
![image](https://user-images.githubusercontent.com/19708921/113746799-9e804c80-96fe-11eb-9e2f-f099a226cd86.png)

2021-04-06 16:44 UTC, thejoefriel commented on client/src/pages/Therapist/Profile/index.js
> +      <Row mt={7}>
Add mb to ensure spacing between the rows in line with wireframes. I'd also suggest removed mt from here and instead apply mb to the row above instead. That way you have a consistent margin styling that is easy to read and edit in the future

![image](https://user-images.githubusercontent.com/19708921/113747202-09ca1e80-96ff-11eb-8a9f-8faa985b3427.png)

2021-04-06 16:44 UTC, thejoefriel commented on client/src/pages/Therapist/Profile/index.js
> +          <Button handleClick={handleSubmit} />
Add text so it says 'Save' not 'Click'

2021-04-06 17:53 UTC, fadeomar commented on client/src/pages/Therapist/Profile/index.js
> +          <Button handleClick={handleSubmit} />
done

2021-04-06 17:59 UTC, fadeomar commented on client/src/pages/Therapist/Profile/index.js
> +      <Row mt={7}>
done

2021-04-06 18:01 UTC, fadeomar commented on client/src/pages/Therapist/Profile/index.js
> +        <Col w={[4, 6, 4]}>
done

2021-04-07 07:50 UTC, thejoefriel requested changes

2021-04-07 07:50 UTC, thejoefriel commented on client/src/pages/Therapist/Profile/index.js
> +          <Button handleClick={handleSubmit} text="Click" />
You've written Click but it should be 'Save' - please always check against wireframes

2021-04-07 07:54 UTC, fadeomar commented on client/src/pages/Therapist/Profile/index.js
> +          <Button handleClick={handleSubmit} text="Click" />
done

2021-04-07 07:55 UTC, thejoefriel approved these changes

2021-04-07 07:55 UTC, merged