72 i can add a client front
yalla-coop/chiltern-music-therapy pull request #120
Opened 2021-04-07 15:11 UTC by fadeomar

#### Issues this PR relates to
#72 
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-04-07 17:52 UTC, thejoefriel requested changes
- [x] Can you change this error message to 'Please only enter the first 2 characters of the postcode'
![image](https://user-images.githubusercontent.com/19708921/113910707-0ef79e00-97d1-11eb-84bc-2ed2769e778c.png)

- [x] If you hit to add a goal but then decide not to add another one and hit next it doesn't let you know. As long as they have provided at least one goal (and category) we should let them hit next and just tidy the array: https://www.loom.com/share/883aae7cbbc94e2c86037aeaf865eca4

- [x] Copied! appears immediately on the page. This should only happen if they then select to copy the link: https://www.loom.com/share/57f508bfa0cc4934ad348b35effc04b5

2021-04-07 17:52 UTC, thejoefriel commented on client/src/validation/err-msgs.js
> +export const AT_LEAST_ADD_ONE = 'It must be at least one gaol';
This is a typo. It should be 'You must add at least one therapy goal'

2021-04-07 18:12 UTC, fadeomar commented on client/src/validation/err-msgs.js
> +export const AT_LEAST_ADD_ONE = 'It must be at least one gaol';
done

2021-04-08 09:34 UTC, thejoefriel approved these changes

2021-04-08 09:35 UTC, merged