73 client
yalla-coop/chiltern-music-therapy pull request #132
Opened 2021-04-08 13:35 UTC by thejoefriel

#### Issues this PR relates to
#73

I haven't shown the therapist's image as I believe we need to confirm how this is fetched from AWS once the backend is sorted? Have set up a separate issue for that bit 

=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-04-11 11:50 UTC, RamyAlshurafa requested changes
good work @thejoefriel, just small things
- [x] i was able to tick use my main bio and the textarea wasnt disabled
![image](https://user-images.githubusercontent.com/34629478/114303112-1078dd00-9ad5-11eb-99dd-18c513c82694.png)

2021-04-11 11:50 UTC, RamyAlshurafa commented on client/src/api-calls/therapists-clients.js
> +      `${THERAPISTS_CLIENTS_BASE}/add-new-client`,
```suggestion
      `${THERAPISTS_CLIENTS_BASE}/client`,
```
post method means add new

2021-04-11 11:50 UTC, RamyAlshurafa commented on client/src/api-calls/therapists-clients.js
> +    // return { data: { state, inviteToken: 'http://bit.ly/afjwlejfafjla' } };
```suggestion
```

2021-04-11 11:50 UTC, RamyAlshurafa commented on server/modules/therapist-client/use-cases/create-client.js
> +    const newClient = await TherapistClient.createClient(
```suggestion
    const newTherapistClient = await TherapistClient.createClient(
```

so we can distinguish between this and client as user

2021-04-11 11:50 UTC, RamyAlshurafa commented on server/modules/therapist-client/model/create.js
> +const createClient = async (
```suggestion
const createTherapistClient = async (
```

2021-04-11 11:50 UTC, RamyAlshurafa commented on server/modules/therapist-client/utils/validate-create-client.js
> +  console.log('REAC', data);
```suggestion
```

2021-04-11 11:50 UTC, RamyAlshurafa commented on server/database/models/users/schema.sql
> +  "mobile_number" VARCHAR(50),
why this is not unique?

2021-04-11 11:50 UTC, RamyAlshurafa commented on server/modules/therapist-client/use-cases/create-client.js
> +    const token = buffer.toString('hex');
wondering why didnt you use the `uniqid` library 
its 8 characters so it make the link shorter and readable in the front

2021-04-11 12:32 UTC, thejoefriel commented on server/database/models/users/schema.sql
> +  "mobile_number" VARCHAR(50),
Because it is the number for primary carer and you might end up with a primary carer looking after multiple clients so best to not have it unique for now

2021-04-11 12:32 UTC, thejoefriel commented on server/modules/therapist-client/use-cases/create-client.js
> +    const token = buffer.toString('hex');
Yeah can do.. Will do that now

2021-04-11 12:47 UTC, thejoefriel commented on server/modules/therapist-client/use-cases/create-client.js
> +    const newClient = await TherapistClient.createClient(
done

2021-04-11 12:49 UTC, thejoefriel commented on server/modules/therapist-client/model/create.js
> +const createClient = async (
done and I've updated filenames to keep consistent

2021-04-11 12:50 UTC, thejoefriel commented on server/modules/therapist-client/utils/validate-create-client.js
> +  console.log('REAC', data);
done

2021-04-11 12:53 UTC, thejoefriel commented on server/modules/therapist-client/use-cases/create-client.js
> +    const token = buffer.toString('hex');
done

2021-04-11 15:25 UTC, RamyAlshurafa reviewed
all seems good @thejoefriel 
just when i filled the bio field, then marked select my main bio, it stored the bio i was added in the textarea before it going disabled, i recommend using 
useEffect(
if(useMyMainBio){
setBio(null)
}
)
```

2021-04-12 08:21 UTC, RamyAlshurafa approved these changes

2021-04-12 08:21 UTC, merged