74 > Edit Client Notes
yalla-coop/chiltern-music-therapy pull request #134
Opened 2021-04-08 16:21 UTC by thejoefriel

#### Issues this PR relates to
Closes #74 

**Rebuild database just to tidy up the goals from the dummy data**

=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-04-11 12:35 UTC, RamyAlshurafa requested changes
- [ ] the goals card cause scroll in the y direction on mobile screens (320px)
![localhost_3000_therapist_clients_7_programme_create_description](https://user-images.githubusercontent.com/34629478/114304356-618bcf80-9adb-11eb-9112-17a1fedcbf14.png)

2021-04-11 12:35 UTC, RamyAlshurafa commented on client/src/api-calls/therapists-clients.js
> +    const { data } = await axios.post(
```suggestion
    const { data } = await axios.patch(
```

2021-04-11 12:35 UTC, RamyAlshurafa commented on client/src/api-calls/therapists-clients.js
> +      `${THERAPISTS_CLIENTS_BASE}/edit-client`,
```suggestion
      `${THERAPISTS_CLIENTS_BASE}`,
```
keep it put with base because you edit on the therapist client fields

2021-04-11 12:35 UTC, RamyAlshurafa commented on server/modules/therapist-client/model/update.js
> +const editClientById = async (
```suggestion
const editTherapistClientById = async (
```

2021-04-12 06:14 UTC, thejoefriel commented on client/src/api-calls/therapists-clients.js
> +    const { data } = await axios.post(
done

2021-04-12 06:16 UTC, thejoefriel commented on client/src/api-calls/therapists-clients.js
> +      `${THERAPISTS_CLIENTS_BASE}/edit-client`,
done

2021-04-12 06:20 UTC, thejoefriel commented on server/modules/therapist-client/model/update.js
> +const editClientById = async (
done

2021-04-12 08:35 UTC, RamyAlshurafa approved these changes

2021-04-12 10:11 UTC, merged