65 edit programme
yalla-coop/chiltern-music-therapy pull request #156
Opened 2021-04-13 11:38 UTC by dupreesi

#### Issues this PR relates to

=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-04-13 16:54 UTC, thejoefriel requested changes
- [x] Error messages briefly show up before the content appears. Add a loading status perhaps: https://www.loom.com/share/711a2e8571e94d56a4fcc055775fe4ea
- [ ] Remove or Filter out All in the dropdown of categories for adding new content. This is purely a search option: 
![image](https://user-images.githubusercontent.com/19708921/114590308-7f466980-9c80-11eb-850e-4047c3ce48e8.png)
- [ ] We've forgotten to store or render the document if the therapist chooses to write the content directly (rather than upload or add a link). This means that if you try to add content in this way it throws an error: https://www.loom.com/share/5abb9f742fc247cbb66fa968b7a7befa

2021-04-13 16:54 UTC, thejoefriel commented on client/src/api-calls/programmes.js
> +    const { data } = await axios.post(`${PROGRAMMES_BASE}/update`, formData);
this should probably be patch instead since it's an update

2021-04-13 16:54 UTC, thejoefriel commented on server/modules/content/controllers/remove-content-from-programme.js
> +const removeContentFromProgramme = async (req, res, next) => {
Could be worth adding a check here that the user in the auth is the same therapist linked to the content, e.g. 

```
const contentToDelete = await Content.findContentById(id);

  if (userId !== contentToDelete.therapistLibraryUserId) {
    throw Boom.unauthorized(errorMsgs.UNAUTHORISED_EDIT);
  }
```

2021-04-13 16:54 UTC, thejoefriel commented on server/modules/programme/use-cases/create-programme.js
> +      await ManageCCC({ userId, contentId: _content.id, categories });
Not for this PR but might be worth creating an issue to turn this into an event listener.
Also why does it have a capital M?

2021-04-13 17:56 UTC, dupreesi commented on server/modules/programme/use-cases/create-programme.js
> +      await ManageCCC({ userId, contentId: _content.id, categories });
good idea for sure!, changed to lower case m

2021-04-14 06:45 UTC, thejoefriel approved these changes

2021-04-14 06:45 UTC, merged