273 update admin signup front
yalla-coop/chiltern-music-therapy pull request #286
Opened 2021-08-30 12:57 UTC by fadeomar

#### Issues this PR relates to
#273
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-08-30 14:07 UTC, RamyAlshurafa requested changes

2021-08-30 15:01 UTC, RamyAlshurafa requested changes

2021-08-30 15:27 UTC, fadeomar commented on client/src/pages/Admin/Customise/index.js
> +    setState({ submitAttempt: true });
done

2021-08-30 15:28 UTC, fadeomar commented on client/src/pages/Admin/Signup/index.js
> +    setState({ submitAttempt: true });
done

2021-08-30 15:35 UTC, fadeomar commented on client/src/pages/Admin/Customise/index.js
> +          <T.H3 weight="bold" mb="3">{`https://www.duetplatform.com/${
done

2021-08-30 15:37 UTC, fadeomar commented on client/src/pages/Admin/Customise/index.js
> +            category={content.fileCategories.image}
done

2021-08-31 13:47 UTC, RamyAlshurafa requested changes
- [x] color and spacing in this section is not the same with figma
![Screenshot from 2021-08-31 16-36-18](https://user-images.githubusercontent.com/34629478/131512304-c26a4d7b-a869-4767-8fd6-0c9367496ae3.png)
- [x] the validation doesn't work for organisation name
  ![Screenshot from 2021-08-31 16-38-48](https://user-images.githubusercontent.com/34629478/131512620-271012b9-717f-4283-8075-3b14ba73e2e2.png)

2021-08-31 13:47 UTC, RamyAlshurafa commented on client/src/pages/Admin/Signup/index.js
> +      history.push(navRoutes.ADMIN.Complete);
this is undefined

2021-08-31 13:47 UTC, RamyAlshurafa commented on client/src/validation/schemas/unique-link.js
> +import { fields, createSchema, validate as _validate } from '..';
name the file same name with the page

2021-08-31 13:47 UTC, RamyAlshurafa commented on client/src/validation/fields.js
> +export const urlLink = string()
this is not link, its slug

2021-08-31 14:14 UTC, fadeomar commented on client/src/pages/Admin/Signup/index.js
> +      history.push(navRoutes.ADMIN.Complete);
done

2021-08-31 14:17 UTC, fadeomar commented on client/src/validation/schemas/unique-link.js
> +import { fields, createSchema, validate as _validate } from '..';
done

2021-08-31 14:19 UTC, fadeomar commented on client/src/validation/fields.js
> +export const urlLink = string()
done

2021-08-31 14:22 UTC, RamyAlshurafa approved these changes

2021-08-31 14:22 UTC, merged