278 update client sign up
yalla-coop/chiltern-music-therapy pull request #291
Opened 2021-08-31 13:57 UTC by fadeomar

#### Issues this PR relates to
#278 
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-09-02 07:24 UTC, RamyAlshurafa requested changes
- [x] on my account it updates the number even if there is a validation error https://www.loom.com/share/e34bc9b85ef644cdb819004d8faf3383
- [x] welcome page doesn't pre fill the contact number, therapist is able to add contact number for the client when invites them, so on that stage the client would have a phone number stored in the db

2021-09-02 07:24 UTC, RamyAlshurafa commented on client/src/pages/General/Welcome/AddPhoneNumber.js
> +      contactByPhone: !contactByPhone,
?

2021-09-02 07:24 UTC, RamyAlshurafa commented on client/src/pages/General/Welcome/AddPhoneNumber.js
> +      setError('');
should errors be object or string? in can see its an object in line 29

2021-09-02 07:24 UTC, RamyAlshurafa commented on client/src/pages/General/Welcome/AddPhoneNumber.js
> +      setError('');
also use `errors, setErrors` would be better naming

2021-09-02 07:24 UTC, RamyAlshurafa commented on client/src/pages/General/Welcome/index.js
> +      {numId === 5 && user.role === 'CLIENT' ? (
use constants

2021-09-02 07:24 UTC, RamyAlshurafa commented on server/modules/user/controllers/index.js
> +router.post(
patch

2021-09-02 13:08 UTC, fadeomar commented on client/src/api-calls/users.js
> +    await axios.post(`${USERS_BASE}/update-phone-number`, data);
done

2021-09-02 13:11 UTC, fadeomar commented on client/src/pages/General/Welcome/AddPhoneNumber.js
> +      contactByPhone: !contactByPhone,
this is because the question syntax `Do not contact me by phone`

2021-09-02 13:13 UTC, fadeomar commented on client/src/pages/General/Welcome/AddPhoneNumber.js
> +      setError('');
done

2021-09-02 13:14 UTC, fadeomar commented on client/src/pages/General/Welcome/index.js
> +      {numId === 5 && user.role === 'CLIENT' ? (
done

2021-09-02 13:14 UTC, fadeomar commented on server/modules/user/controllers/index.js
> +router.post(
done

2021-09-05 11:22 UTC, RamyAlshurafa requested changes

2021-09-05 11:22 UTC, RamyAlshurafa commented on client/src/pages/General/Welcome/AddPhoneNumber.js
> +      contactByPhone: !contactByPhone,
then rename it to something like `dontContactByPhone`

2021-09-05 13:38 UTC, RamyAlshurafa approved these changes

2021-09-05 13:38 UTC, merged