Create All Therapists page
yalla-coop/chiltern-music-therapy pull request #296
Opened 2021-09-01 13:12 UTC by AdhamHaisami

Relates #281

#### Issues this PR relates to

=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-09-07 11:19 UTC, RamyAlshurafa requested changes

2021-09-07 11:19 UTC, RamyAlshurafa commented on server/modules/user/use-cases/update-user-role.js
> +const updateUserRole = async ({ id, role }) => {
add validation here, don't rely on the role from the client

2021-09-07 11:19 UTC, RamyAlshurafa commented on server/database/models/users/schema.sql
> +  "is_active" BOOLEAN DEFAULT TRUE,
we have status, so no need for this

2021-09-07 11:19 UTC, RamyAlshurafa commented on client/src/pages/Admin/index.js
> +            allowedRoles={[roles.ADMIN]}
>  This controller and page is authorised to be used / viewed by both admin and super admin

2021-09-07 11:19 UTC, RamyAlshurafa commented on client/src/constants/roles.js
> +};
DEACTIVATED is status, not role

2021-09-07 11:19 UTC, RamyAlshurafa commented on client/src/api-calls/users.js
> +const updateUserRole = async (updates, { options } = {}) => {
i can see the api url is not related to roles, so I think the name should be updateUser,
- [ ] also the update should be /users/id

2021-09-07 11:19 UTC, RamyAlshurafa commented on client/src/api-calls/users.js
> +      `${USERS_BASE}/deactivate-user`,
```suggestion
      `${USERS_BASE}/${id}/deactivate`,
```

2021-09-07 11:19 UTC, RamyAlshurafa commented on server/modules/organisation/controllers/index.js
> +router.get('/:id/therapists', authenticate(), getAllTherapists);
authorization

2021-09-07 11:19 UTC, RamyAlshurafa commented on server/modules/user/controllers/index.js
> +  deactivateUser,
authorisation

2021-09-07 11:19 UTC, RamyAlshurafa commented on server/modules/user/controllers/update-user.js
> +      role: [role],
send it as single role, the usecase should handle it

2021-09-07 11:19 UTC, RamyAlshurafa commented on server/modules/user/use-cases/login.js
> +      const myTherapist = await TherapistClient.findTherapistByClientId(
add the same logic for getUserInfo controller

2021-09-08 11:14 UTC, AdhamHaisami commented on client/src/pages/Admin/index.js
> +            allowedRoles={[roles.ADMIN]}
done

2021-09-08 11:14 UTC, AdhamHaisami commented on server/database/models/users/schema.sql
> +  "is_active" BOOLEAN DEFAULT TRUE,
done

2021-09-08 11:18 UTC, AdhamHaisami commented on client/src/constants/roles.js
> +};
done

2021-09-08 11:39 UTC, AdhamHaisami commented on client/src/api-calls/users.js
> +const updateUserRole = async (updates, { options } = {}) => {
done

2021-09-08 12:01 UTC, AdhamHaisami commented on client/src/api-calls/users.js
> +      `${USERS_BASE}/deactivate-user`,
done

2021-09-08 12:08 UTC, AdhamHaisami commented on server/modules/organisation/controllers/index.js
> +router.get('/:id/therapists', authenticate(), getAllTherapists);
done

2021-09-08 12:16 UTC, AdhamHaisami commented on server/modules/user/controllers/index.js
> +  deactivateUser,
done

2021-09-08 12:20 UTC, AdhamHaisami commented on server/modules/user/controllers/update-user.js
> +      role: [role],
done

2021-09-08 14:14 UTC, AdhamHaisami commented on server/modules/user/use-cases/update-user-role.js
> +const updateUserRole = async ({ id, role }) => {
done

2021-09-13 11:16 UTC, RamyAlshurafa commented on server/database/models/users/schema.sql
> +  "is_active" BOOLEAN DEFAULT TRUE,
still used in
`const findTherapistByClientId = async (id) => {`

2021-09-13 11:47 UTC, RamyAlshurafa requested changes
- [x] can't login as admin
- [ ] show therapists for one organisations
- [ ] update page url /admin/organisations/:id/therapists
- [ ] update API endpoint /organisations/:id/therapists

2021-09-16 10:45 UTC, RamyAlshurafa approved these changes

2021-09-16 10:46 UTC, merged