305 Update navbar and create accessibility page
yalla-coop/chiltern-music-therapy pull request #313
Opened 2021-09-15 11:27 UTC by Israa91

#### Issues this PR relates to

=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-09-20 11:33 UTC, fadeomar requested changes
hey @Israa91 nice work, but there is some points need to fix : 
  - [x] there is padding wrapping the all page not like the other pages, you can see the different on the wireframes .
![image](https://user-images.githubusercontent.com/39485495/133988598-a0665818-1837-4930-b4c7-efcbc9c2cce3.png)

  - [x] you must add target="_blank" for the external links to open them on a new tab and not lose the app 
  - [ ] when you add external links please add them to the constants file and import them as variables you can find on src > constants > nav-routes > EXTERNAL

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/index.js
> +              Go to “View” on the menu bar > Select text size / zoom
```suggestion
              Go to “View” on the menu bar &gt; Select text size / zoom
```
invalid charcter

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/index.js
> +              Go to “View” on the menu bar > Select text size / zoom.
```suggestion
              Go to “View” on the menu bar &gt; Select text size / zoom.
```

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/style.js
> +`;
this covers our Typograpghy common component as `Typograpghy.Link` and you can pass props like underline and color and external to achieve your goal here

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/index.js
> +              </S.A>{' '}
```suggestion
              <T.Link external underline color="blue" to="https://www.google.fr/">
                Click here to download Voice Aloud Reader
              </T.Link>{' '}
```

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/index.js
> +              <S.A href="https://www.google.fr/">
```suggestion
              <T.Link external underline color="blue" to="https://www.google.fr/">
```

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/index.js
> +              <S.A href="https://www.google.fr/">
```suggestion
              <T.Link external underline color="blue" to="https://www.google.fr/">
```

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/index.js
> +          </T.P>
this doesn't match the wireframe, those are three Paragraphs not one!!

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/index.js
> +        <Row mb="6" mbM="4">
remove unused Row you can add the margin props to the Col component too

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/index.js
> +          <Col w={[4, 12, 12]}>
```suggestion
          <Col w={[4, 12, 12]} mb="6" mbM="4">
```

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/index.js
> +          <Col w={[4, 12, 12]}>
```suggestion
          <Col w={[4, 12, 12]}  mb="6" mbM="4">
```
remove unused Row you can add the margin props to the Col component too

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/index.js
> +          <Col w={[4, 12, 12]}>
```suggestion
          <Col w={[4, 12, 12]} mb="6" mbM="4">
```
remove unused Row you can add the margin props to the Col component too

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/index.js
> +            <T.P color="gray8" weight="bold">
```suggestion
        <Row >
          <Col w={[4, 12, 12]} mb="6" mbM="4">
            <T.P color="gray8" weight="bold">
```
remove unused Row you can add the margin props to the Col component too

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/index.js
> +        <Row mb="6" mbM="4">
too many Rows

2021-09-20 11:33 UTC, fadeomar commented on client/src/pages/General/AccessibilityPage/index.js
> +      </Row>
the only reason to use `Row` component is to wrap Col`s component, you can render the Line component without putting it on Row and add the margin value to it directly

2021-09-20 12:54 UTC, Israa91 commented on client/src/pages/General/AccessibilityPage/index.js
> +              Go to “View” on the menu bar > Select text size / zoom
Done

2021-09-20 12:55 UTC, Israa91 commented on client/src/pages/General/AccessibilityPage/index.js
> +              Go to “View” on the menu bar > Select text size / zoom.
Done

2021-09-20 12:58 UTC, Israa91 commented on client/src/pages/General/AccessibilityPage/index.js
> +              <S.A href="https://www.google.fr/">
Done

2021-09-20 13:21 UTC, Israa91 commented on client/src/pages/General/AccessibilityPage/index.js
> +              <S.A href="https://www.google.fr/">
Done

2021-09-20 13:52 UTC, Israa91 commented on client/src/pages/General/AccessibilityPage/index.js
> +      </Row>
Done

2021-09-20 13:52 UTC, Israa91 commented on client/src/pages/General/AccessibilityPage/index.js
> +        <Row mb="6" mbM="4">
Done

2021-09-20 13:53 UTC, Israa91 commented on client/src/pages/General/AccessibilityPage/index.js
> +            <T.P color="gray8" weight="bold">
Done

2021-09-20 13:53 UTC, Israa91 commented on client/src/pages/General/AccessibilityPage/index.js
> +          <Col w={[4, 12, 12]}>
Done

2021-09-20 13:53 UTC, Israa91 commented on client/src/pages/General/AccessibilityPage/index.js
> +          <Col w={[4, 12, 12]}>
Done

2021-09-20 13:53 UTC, Israa91 commented on client/src/pages/General/AccessibilityPage/index.js
> +          <Col w={[4, 12, 12]}>
Done

2021-09-20 13:53 UTC, Israa91 commented on client/src/pages/General/AccessibilityPage/index.js
> +        <Row mb="6" mbM="4">
Done

2021-09-20 13:53 UTC, Israa91 commented on client/src/pages/General/AccessibilityPage/index.js
> +          </T.P>
Done

2021-09-20 19:46 UTC, Israa91 commented on client/src/components/Navbar/style.js
> +  margin-left: -38px;
Done

2021-09-20 19:46 UTC, Israa91 commented on client/src/components/Navbar/style.js
> +  width: 377px;
Done

2021-09-20 19:48 UTC, Israa91 commented on client/src/components/Navbar/style.js
> +    margin-left: -35px;
Done

2021-09-20 19:53 UTC, Israa91 commented on client/src/pages/General/AccessibilityPage/style.js
> +`;
Done

2021-09-21 06:18 UTC, thejoefriel requested changes
- [ ] navigation menu is missing from the accessibility page. 
![image](https://user-images.githubusercontent.com/19708921/134120495-62de83cc-b490-4597-8c68-b245618edf2f.png)

2021-09-21 06:18 UTC, thejoefriel commented on client/src/components/AccessibilityBar/index.js
> +    <S.Div1>
Not something to change here but in future think about more descriptive names for styled elements (e.g. Container, InnerContent)

2021-09-21 06:18 UTC, thejoefriel commented on client/src/components/Navbar/style.js
> +  padding: inherit;
do display flex and align-items center and this should vertically align the contents.  You'll notice that the arrow icon isn't quite in the center vertically as it should be

2021-09-21 08:27 UTC, fadeomar commented
some notes no fix: 
  - [ ] spacing on mobile 
![image](https://user-images.githubusercontent.com/39485495/134137143-0a30c1f4-8cbb-4942-8d82-96acedbcbbaa.png)
  - [ ] clicking contact us direct me to `http://localhost:3000/digital@chilternmusictherapy.co.uk`

2021-09-21 08:27 UTC, fadeomar approved these changes

2021-09-21 08:29 UTC, merged