303 protected programmes
yalla-coop/chiltern-music-therapy pull request #314
Opened 2021-09-15 15:40 UTC by RamyAlshurafa

#### Issues this PR relates to
Close #303 

=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-09-16 19:36 UTC, thejoefriel commented on client/src/api-calls/programmes.js
> +    const { data } = res;
Why destructure res but then wrap up the data back into an object again?

2021-09-16 19:41 UTC, thejoefriel requested changes
- [ ] On the password since we've put on validation, add the helper icon to show them what they need to include for a password 
- [x] When the client is on the programme the menu should be empty

2021-09-16 19:41 UTC, thejoefriel commented on client/src/pages/Therapist/CreateProgram/index.js
> +    // TODO: undo this
what is this? Would be good to add more context in the notes and create an issue if this is something to be done in the future

2021-09-19 11:19 UTC, RamyAlshurafa commented on client/src/api-calls/programmes.js
> +    const { data } = res;
this is because im not able to make destructure with let

2021-09-19 11:22 UTC, RamyAlshurafa commented on client/src/pages/Therapist/CreateProgram/index.js
> +    // TODO: undo this
done

2021-09-20 17:17 UTC, merged