25 create layout
yalla-coop/chiltern-music-therapy pull request #85
Opened 2021-03-30 13:32 UTC by fadeomar

#### Issues this PR relates to
#25 
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-03-30 15:58 UTC, thejoefriel requested changes
Hey @fadeomar since you've started putting graphics in, I'd suggest it's worth finishing it, so can you assign yourself to this issue please and complete the checklist

- [x] Only welcome3 (the example image you've put in) seems to be working. All the others can't find the file https://www.loom.com/share/d64ea58c7fb04032a41ed33b42d27644
- [ ] Only 5 images are upload (I believe all the desktop ones). Please add all 7 x Large ones and 8 x Small ones. Label them as such so we can switch (I know the images are very similar but the mobile has more cropping and it'll be easier just to deal with it as a separate image rather than doing overflow hidden stuff etc)

2021-03-30 15:58 UTC, thejoefriel commented on client/src/components/Layout/Info/index.js
> +        <Image image={image} customStyle={{ width: '100%' }} />
Needs to render a different image (the small version) if in mobile. The small version has more cropping and some minor changes even though it looks similar, so it's best to have two versions

2021-03-30 15:58 UTC, thejoefriel commented on client/src/components/Layout/General/style.js
> +export const Border = styled.div`
Generally this is fine but it does create an extra element which can make it less accessibility friendly. Could be worth using :before or :after on the header itself

2021-03-31 08:53 UTC, fadeomar commented on client/src/components/Image/index.js
> +  margin: ${({ margin }) => margin || '0'};
done

2021-03-31 08:54 UTC, fadeomar commented on client/src/components/Image/index.js
> +const Image = ({ image, width, height, margin, alt, customStyle }) => {
done

2021-03-31 10:09 UTC, fadeomar commented on client/src/components/Layout/General/style.js
> +    display: none;
done

2021-03-31 11:56 UTC, fadeomar commented on client/src/components/Layout/Info/index.js
> +        <Image image={image} customStyle={{ width: '100%' }} />
done

2021-03-31 12:35 UTC, thejoefriel approved these changes

2021-03-31 12:35 UTC, merged